name: office-automation_

include:
  - ./docker/orchestration/orchestration.yml
  - ./docker/postgres/postgres.yml
  - ./docker/directus/directus.yml
  - ./docker/minio/minio.yml
  - ./docker/keydb/keydb.yml
  - ./docker/mailhog/mailhog.yml
  
  # BullMQ Workers
  - ./docker/workers/workers.yml
  
  # Unused services for current simple workflow:
  # - ./docker/temporal/temporal.yml
